### ISSUE TITLE
no use of zulumount as a user

### ISSUE THREAD

**Issue by harley-peter** [mhogomchungu/zuluCrypt#103]
Hello,
in the manual of zulucrypt is described that also a normal user can us zulumount if he is in the group zulumount but it does not work. Only root can use the tools. That does not make sense in multi user system. Is there a possibility to change the permission?

**Comment by harley-peter** [comment]
Hello,
I use the version 5.4.0 and I use it in Siduction which is based on Debian unstable.

Regards
Peter

**Comment by mhogomchungu** [comment]
zuluCrypt in debian and its derivatives do not have the user experience i want and there is nothing i can do about it because i am not a zuluCrypt packager in these distributions.

I provide debian binary packages in zuluCrypt home page[1] and these packages give the experience i want and i suspect the experience you expect.

Uninstall the version of zuluCrypt you got from your distribution and then either install one of the debian packages i distribute or build from source and then we can then discuss zuluCrypt experience you see after you use it the way i want you to use it.

[1] https://mhogomchungu.github.io/zuluCrypt/

**Comment by harley-peter** [comment]
Hello,
my distribution has installed the following packages:
`ii  libzulucrypt-exe1.2.0:amd64                     5.4.0-2                         amd64        provide the main functions of zulucrypt
ii  libzulucrypt1.2.0:amd64                         5.4.0-2                         amd64        provide the functions of zulumount
ii  libzulucryptpluginmanager1.0.0:amd64            5.4.0-2                         amd64        provides support for plugins
ii  zulucrypt-cli                                   5.4.0-2                         amd64        tool for encrypting volumes
ii  zulucrypt-gui                                   5.4.0-2                         amd64        graphical front end for zulucrypt-cli
ii  zulupolkit`

Do I need the packages libzulucrypt-exe, libzulucryptpluginmanager and zulupolkit? They are not in your packages.

**Comment by mhogomchungu** [comment]
Lets do one thing at a time.

Do you want to use GUI components of the project or CLI components?

If GUI components, are you complaining about the polkit prompt you get when you start GUI components? If yes to both of the questions this paragraph, then you can silence the polkit prompt that asks for root's password by changing the polkit file at: ```/usr/share/polkit-1/actions/org.zulucrypt.zulupolkit.policy``` and modify like that says ```<allow_active>auth_admin</allow_active>``` to ```<allow_active>yes</allow_active>```

**Comment by harley-peter** [comment]
Thanks for that hint, it works. :-) Also with the distribution version of zulucrypt.
