### ISSUE TITLE
veracrypt support

### ISSUE THREAD

**Issue by arigit** [mhogomchungu/zuluCrypt#11]
Please add VeraCrypt support (most promising truecrypt derivative). TrueCrypt is obsolete at this point.

There is a current fork of tcplay that supports it (veracrypt's own fork)

References
https://github.com/bwalex/tc-play/pull/65
https://github.com/veracrypt/tc-play

**Comment by mhogomchungu** [comment]
Best place for zuluCrypt to get support for veracrypt volumes is from cryptsetup[2] since cryptsetup is a required dependency(tcplay is an optional dependency).

I have just opened a request[1] for cryptsetup to add support for veracrypt volumes and i will add it if/when cryptsetup adds it first.

[1] https://code.google.com/p/cryptsetup/issues/detail?id=245
[2] https://code.google.com/p/cryptsetup/

**Comment by mhogomchungu** [comment]
request for veracrypt support in cryptsetup can be tracked here: https://code.google.com/p/cryptsetup/issues/detail?id=245

**Comment by mhogomchungu** [comment]
git version of zuluCrypt [1] now supports VeraCrypt volumes.

you will also need git version of cryptsetup since the support there was added less than a day ago.

first build and install git version of cryptsetup and then build and install git version of zuluCrypt and zuluCrypt-gui will then show options to unlock VeraCrypt volumes.

will appreciate if you could test and report back.

[1] https://github.com/mhogomchungu/zuluCrypt/commit/f513117619e9452112285faf4120724845764e04

**Comment by mhogomchungu** [comment]
zuluCrypt can now create veracrypt volumes too.You can get the version that does that now from here: https://github.com/mhogomchungu/tc-play.

git versions of cryptsetup and zuluCrypt are also still required.

**Comment by mhogomchungu** [comment]
An update to this issue.

cryptsetup 1.6.7 was released couple of days ago and it supports unlocking VeraCrypt volumes.

latest released version of zuluCrypt(4.7.5) can now unlock VeraCrypt volumes if it was build against cryptsetup 1.6.7 or later versions.

zuluCrypt git version and future versions will contain an internal copy of tcplay that supports creation of VeraCrypt volumes as well as TrueCrypt volume.

the above two means,if you have cryptsetup 1.6.7 or later versions installed,then zuluCrypt git version and all future versions will automatically gain support for opening and creating VeraCrypt volumes,

**Comment by arigit** [comment]
thanks for the continued support. Using the latest cryptsetup and zulucrypt and working fine (fedora 21)

**Comment by mhogomchungu** [comment]
updating this bug report since it now contains "wrong" information caused by recent changes in zuluCrypt.

zuluCrypt now ships with an internal copy of tcplay[1] and this version has support for creation and unlocking of VeraCrypt volumes.This means a particular minimum version of cryptsetup is no longer required to gain VeraCrypt support.

This means zuluCrypt even in "old" distributions like debian 7 that ships with version 1.4.x of cryptsetup has full support for VeraCrypt volumes.

[1] https://github.com/bwalex/tc-play
