### ISSUE TITLE
Check if plain dm-crypt with non-0 offset works

### ISSUE THREAD

**Issue by HulaHoopWhonix** [mhogomchungu/zuluCrypt#115]
I tried to make a deniable container using the instructions in the pdf manual, but whnever I type the password and set the offset size, it does not accept the key. 

I want to make sure this is not caused by an error on my part.

**Comment by mhogomchungu** [comment]
How did you create the volume.

What offset value did you use when creating the volume

What offset value did you us when unlocking the volume.

**Comment by HulaHoopWhonix** [comment]
I chose it's size to be 50MB

Set offset to 20MB

Attempted opening it with offset @ 30MB

**Comment by mhogomchungu** [comment]
Open it with offset of "20m"

**Comment by mhogomchungu** [comment]
Tested in on debian 9 and it works fine.

**Comment by HulaHoopWhonix** [comment]
>Tested in on debian 9 and it works fine.

Please test on Buster (Debian 10) the problem is still there.

**Comment by mhogomchungu** [comment]
I tested it on debian buster installed in virtualbox and the below screenshot proves it.

You are getting confused somewhere

![Screenshot_20190430_223742](https://user-images.githubusercontent.com/3496115/56988435-b3f6ae80-6b98-11e9-9979-ea8106c99a9c.png)

**Comment by mhogomchungu** [comment]
Mouse over the offset field when unlocking a volume to get a tool tip with directions on how to enter the offset, "30MB" for example is not a valid offset, it should be "30m".

The git version to be released tomorrow would accept "30MB" as an offset since its a lot more forgiving[1]

[1] https://github.com/mhogomchungu/zuluCrypt/blob/340ea845bd8009bd3d4100ddb30d46c684bbc6d3/zuluCrypt-cli/lib/open_plain.c#L73

**Comment by HulaHoopWhonix** [comment]
You're right. I hadn't noticed the ephermeral notice that comes up when you move the mouse on there. I was typing just "20" instead of m. It now works thanks.

So how does one use this deniably so another password would just show a different section of the container with other info?

**Comment by mhogomchungu** [comment]
My use case for this feature is a 1TB external hard drive with two volumes.

The first volume at offset 0 is an unencrypted fat filesystem everybody notices and can use without providing any password and the second is a plain dm-crypt at offset 700MB that only i know its there and the password to unlock it.

User of this feature will have to know both the passwrod to unlock a volume and the location of a volume.

Best things about this feature is that a single container can have as my hidden volumes as you want.

Worst thing about this feature is that there is no protection of the hidden volume. Write too much in the outer volume and all inner volumes will silently be corrupted so use with care.

Closing this one since the asked question is now answered but feel free to continue posting if anything else comes up.

**Comment by HulaHoopWhonix** [comment]
Thanks for your patience.
>My use case for this feature is a 1TB external hard drive with two volumes.
I see so it has to be using the Encrypted Container in a Harddrive option?

**Comment by mhogomchungu** [comment]
That was my use case, you can have the plain dm-crypt volume in container files at any offset.

I just released version 5.5.0[1] of zuluCrypt and one of the feature in this release is the ability to create these plain dm-crypt volumes at the end of existing files.

With this new ability, you can create a plain dm-crypt volume at the end of a video file and most video players will play the file just fine without noticing the encrypted volume at the end.

[1] https://github.com/mhogomchungu/zuluCrypt/releases/tag/5.5.0
