### ISSUE TITLE
Problem unlocking the DM-CRYPT volume

### ISSUE THREAD

**Issue by git70** [mhogomchungu/zuluCrypt#129]
Creating a new container goes without problems.

When trying to decrypt the volume I have the message:
"Volume could not be opened with the presented key".
The password is definitely correct (I did tests).
It only works correctly if I choose default encryption (first in the drop-down list: aes.cbc-essiv:sha256.256.sha256).

I have some suspicion:
The problem may be that the encryption algorithm cannot be selected because the icon is gray (is this option required for decryption or does the program recognize itself?)

![screen2](https://user-images.githubusercontent.com/49098178/65074098-6c7c8d80-d994-11e9-94bc-9c87c264549a.png)

The problem occurs on version 5.6.0, the Ubuntu 18.04 binary package downloaded from the project website.
The problem does NOT occur on version 5.4.0 from the official Ubuntu / Mint repository.
Operating system: Linux Mint 19.2 fresh installation
zuluCrypt-cli - test: All Passed

**Comment by mhogomchungu** [comment]
The application use the default option which is the first one on the list if the user does not set it.

This bug was introduced in 5.6.0 when i added "VeraCrypt System" to the list and it took the position of PLAIN dm-crypt entry and i didnt update all the relevant code. Select "VeraCrypt System" and you will see the button is active again with PLAIN dm-crypt options.

The problematic line is this one[0], PLAIN dm-crypt is no longer at position "2" but at position "3".

Closing this one but will appreciate a confirmation that it works now.

This[1] commit fixed the bug and you can get binary packages from here[2]. The 

[0] https://github.com/mhogomchungu/zuluCrypt/commit/170f4b3189415304789a8874e1a1e684c81e1783#diff-c4ba9f463093fa00bcdbb3977f37da5dL179

[1] https://github.com/mhogomchungu/zuluCrypt/commit/170f4b3189415304789a8874e1a1e684c81e1783

[2] https://download.opensuse.org/repositories/home:/mhogomchungu/xUbuntu_18.04/amd64/

**Comment by git70** [comment]
Now it works fine here, but there is still a problem in the Favorites section. Please check.
Many thanks for the speed of action!

**Comment by mhogomchungu** [comment]
I am not aware of any problems in the favorites section, what problem are you seeing?

**Comment by git70** [comment]
Inactive encryption selection button for dm-crypt when opening the container.
Similar to the problem above: The VeraCrypt System selection sequence and only then PLAIN dm-crypt works approx.

**Comment by mhogomchungu** [comment]
>Inactive encryption selection button for dm-crypt when opening the container.

This part is solved in the latest git and binary package i posted above, right?

> Similar to the problem above: The VeraCrypt System selection sequence and only then PLAIN dm-crypt works approx.

This makes no sense to me.

Can you give step by step instruction i can to reproduce the problem?

**Comment by git70** [comment]
Hmm...
I can't reproduce the problem now. 
Maybe I got the test computers wrong and checked the program version before patches.
Forgive me!

**Comment by mhogomchungu** [comment]
FYI, you can customize the list of dm-crypt crypto options you see when you click the button or when you create a plain dm-crypt volume by changing the value of ```PlainDmCryptOptions``` key in ```zuluCrypt.conf``` file located at ~/.config/zuluCrypt.

The first entry is used as the default option and you can change the default by modifying the list.

**Comment by mhogomchungu** [comment]
> Inactive encryption selection button for dm-crypt when opening the container.
> Similar to the problem above: The VeraCrypt System selection sequence and only then PLAIN 
> dm-crypt works approx.

I can reproduce the problem you were talking about here, the button became inactive again when a wrong password is entered and the only way to make it active again is to select a different option like "VeraCrypt System" and then re-selecting "PLAIN dm-crypt".

Updated binary packages has a solution to the problem.

**Comment by git70** [comment]
OK Thx!
