### ISSUE TITLE
Cannot create container

### ISSUE THREAD

**Issue by git70** [mhogomchungu/zuluCrypt#130]
Suddenly a new problem appeared :(
When I try to create any container, I get the message:

![screen](https://user-images.githubusercontent.com/49098178/65364951-a4dece80-dc15-11e9-923d-26cc0ae9a108.png)

Help!

**Comment by mhogomchungu** [comment]
That missing symbol was added about a week or two ago.

Did you install zuluCrypt or update your system before the problem started?

I can think of two possibilities of why you are getting that error.

Either you are using zuluCrypt from someplace else(your distribution??) and their version does not include this symbol and you should report the problem to them since they didnt package zuluCrypt properly..

Or you installed zuluCrypt from two different places and there is a package mismatch and the CLI is from a newer package while the library is from an older package.

**Comment by git70** [comment]
I have version 5.6.0.1566189429 installed from your binary package for Ubuntu 18.04.
I installed it about one or two weeks ago but didn't use it until yesterday.
Of course, there were certainly some system updates in the meantime (Linux Mint 19.2).
I don't use ZuluCrypt in other places.

**Comment by mhogomchungu** [comment]
From here[1], the packages you are supposed to install are:

1. libzulucrypt1_5.6.0.1568786885.170f4b31-0_amd64.deb
2. zulucrypt-cli_5.6.0.1568786885.170f4b31-0_amd64.deb
3. zulucrypt-gui_5.6.0.1568786885.170f4b31-0_amd64.deb

Maybe the problem is caused by you not installing the first package in the above list.

[1] https://download.opensuse.org/repositories/home:/mhogomchungu/xUbuntu_18.04/amd64/

**Comment by git70** [comment]
> Maybe the problem is caused by you not installing the first package in the above list.
It is installed in the same version as the others :(

**Comment by mhogomchungu** [comment]
I can not reproduce what you are observing while testing in debian 10.

I have updated the binary packages and install the new ones and see if the problem is still there.

**Comment by git70** [comment]
I reinstalled the same version that was installed 5.6.0.1566189429 (I removed all 4 packages and installed again) and the problem disappeared. WTF?
