### ISSUE TITLE
[Feature Request] Adding ETA information to the progress window

### ISSUE THREAD

**Issue by git70** [mhogomchungu/zuluCrypt#135]
![screen](https://user-images.githubusercontent.com/49098178/65688650-c99ad200-e06b-11e9-8781-4dd672ba2e4e.png)

When writing random data to a file or device, it would be nice to see the estimated end time.
Particularly useful for large volumes.

**Comment by mhogomchungu** [comment]
The explanation of why the functionality is now there is here[1]. Its been years since i last investigated it so perhaps its time to revisit the functionality.

The problem i saw was that a burst of fast writes will happen reducing estimated time remaining by a lot followed by prolonged stalling increasing estimated time remaining. The ETA was fluctuating too much for my liking.

[1] https://github.com/mhogomchungu/zuluCrypt/blob/d9939ec0ffba743453f8c50c00eeedc9151b05f5/zuluCrypt-gui/erasedevice.cpp#L172

**Comment by git70** [comment]
It seemed to me that continuous writing block by block has a constant speed :(
I don't know if it makes sense, but you can check how it is solved in Timeshift, FreeFileSync and VeraCrypt. They also have fluctuations, but it's better than no information...

**Comment by mhogomchungu** [comment]
Done and the binary git package has the functionality.
![Screenshot_20190928_091356](https://user-images.githubusercontent.com/3496115/65812535-02a08700-e1d1-11e9-9e52-d5c2f64c8913.png)

![Screenshot_20190928_091331](https://user-images.githubusercontent.com/3496115/65812531-f0bee400-e1d0-11e9-8745-79e315142508.png)

**Comment by git70** [comment]
Looks wonderful :)
I will wait with the update until you look at error 132
