### ISSUE TITLE
Additional arguments for Truecrypt/Veracrypt volumes

### ISSUE THREAD

**Issue by xp499** [mhogomchungu/zuluCrypt#146]
According to this (http://manpages.ubuntu.com/manpages/cosmic/man8/cryptsetup.8.html), there's a need to indicate that a Truecrypt/Veracrypt is a system volume in order to unlock it by means of "--tcrypt-system" flag.

How can we indicate those extra/unsupported flags by zuluCrypt (cli & gui)? Is there anywhere an extra option to inidicate those extra flags as options by the current release of app? Would it be nice to implement such a feature instead of giving support for each option that exists and shall exist?

I'm not being rude nor requesting anything, just asking for information and making some proposals, and i apologize if this has already been answered by the team (i searched for it a lot while around, but didn't found anything regarding to this).

**Comment by mhogomchungu** [comment]
What version of zuluCrypt are you using? The latest version 5.7.1 has the option as seen in the image below.

Trying to unlock a TrueCrypt volume does not  take long and zuluCrypt does not give any options and it tries everything in the following order:

1. Try to unlock as a normal volume.
2. Try to unlock as a normal volume using backup header.
3. Try to unlock as a hidden volume.
4. Try to unlock as a system volume.

Trying to unlock a VeraCrypt volumes takes a very long time if a wrong password is used and a user has to manually select this option and default actions are:
1. Try to unlock as a normal volume.
2. Try to unlock as a hidden volume.

A user has to select if they want to try as a system volume. The GUI option is seen in the image below, CLI option is "-t vcrypt-sys".

![Screenshot_20200705_071209](https://user-images.githubusercontent.com/3496115/86525521-d9fc9a80-be90-11ea-85ac-0c22bda30224.png)

**Comment by xp499** [comment]
Jesus christ, my bad i was referring to zuluMount.

So sorry about.

Anyways I can't find any option, but if you say it's programmed to try opening volumes in that order trying each kind, maybe it's me failing with the password, but i just set it yesterday, i wouldn't want to think i'm getting crazy or something, lol.

I will stick to zuluCrypt cli that has the option to open it at least. Thanks for remiting me the info about. Anyways is this info in the wiki of zulyCrypt cli or somewhere else?

Maybe i'm just being bad or very slacker at searching also...

Again and anyways, my apologies about wasting your time on giving me support. Believe me when i say ik that this hurts (a lot, that's why i express my sorry beforehand).

**Comment by mhogomchungu** [comment]
When i started this project, i started with zuluCrypt and its mission was to do block device encryption and it can create and unlock them.

Later on, i added zuluMount and its original mission was to do mounting of un-encrypted file systems. Later on, it picked up an ability to unlock TrueCrypt, VeraCrypt, BitLocker and LUKS volumes and it internally uses zuluCrypt to do the actual work and zuluMount cli behaves the same exact way as zuluCrypt cli when unlocking these volumes  and it uses the same "-t" options.

zuluMount gui currently does not support unlocking VeraCrypt volumes that uses PIM values or system volumes for both VeraCrypt and TrueCrypt. 

These options i do not think are documented anywhere. Its been a while since i last updated documentation and they are missing a lot of information. WIll update them soon.

No need to apologize, i welcome questions or any other comments and i don't find them to be annoying because they don't happen often enough to be annoying.

**Comment by mhogomchungu** [comment]
The git version now supports unlocking of VeraCrypt system volume using zuluMount-gui.

![Screenshot_20200707_203419](https://user-images.githubusercontent.com/3496115/86820310-87d69780-c091-11ea-9353-884065ab4cc5.png)
