### ISSUE TITLE
zuluCrypt-cli man page mentions -E and -D but does not describe them

### ISSUE THREAD

**Issue by WenceslaoGrillo** [mhogomchungu/zuluCrypt#152]
zuluCrypt's man page, under "Synopsis", inlcudes the following lines:

> zuluCrypt-cli -E <d> <e> <p|f|h>
> zuluCrypt-cli -D <d> <e> <p|f|h>

And then, in the description for -e we have:

> -e         mode for opening volumes(ro*/rw) when used with -o/-O. path to destination file when used with -E/-D
> -e         mode for managing a truecrypt header when used with -B/-R.Options can be "fde" for volumes that use whole disk
>     encryption,"sys" for a windows system volume.The volume is assumed to be a normal one when the  option  is  not
>     set.

But there is no description for -E and -D. Also, in the Synopsis part, -B and -R do not include mentions of -e.

**Comment by mhogomchungu** [comment]
Thanks for the report and will correct the manpage within a day or two.

-E option is for encrypting a single file.
-D option is for decrypting a single file encrypted with -E option.

I added these options mostly because i had time and keyboard happy and wanted to add any feature i could think of and i think you are better off using gpg if you want to encrypt single files.

These options should be removed because they are no longer supported
```
[ink@localhost ~]$ zuluCrypt-cli -E -d aaa -e xxx
INFORMATION: Functionality currently disabled
[ink@localhost ~]$ zuluCrypt-cli -D -d xxx -e ccc
INFORMATION: Functionality currently disabled
[ink@localhost ~]$ 

```
-B option is for saving header backup and it uses "-z" instead of "-e".
-R option is for restoring a header from a backup and it uses "-z" instead of "-e".

Example uses of -B and -R options
```
/usr/bin/zuluCrypt-cli -B -d "/home/ink/luks.img" -z "/home/ink/luks.img.luksVolumeHeaderBackUp"

/usr/bin/zuluCrypt-cli -R -d "/home/ink/luks.img" -z "/home/ink/luks.img.luksVolumeHeaderBackUp"

```

**Comment by WenceslaoGrillo** [comment]
Thanks to you, for the explanation, and for a fine piece of software!
Please feel free to close the case once you fix it. It will take some time until I can check it, because I'm using my distro's package.

**Comment by mhogomchungu** [comment]
This one is now fixed, thank you.
