### ISSUE TITLE
Not linking cli with lcrypto

### ISSUE THREAD

**Issue by ysangkok** [mhogomchungu/zuluCrypt#16]
I am not using gcrypt and I got the error:

```
make -f zuluCrypt-cli/CMakeFiles/zuluCrypt-cli.dir/build.make zuluCrypt-cli/CMakeFiles/zuluCrypt-cli.dir/build
make[2]: Entering directory '/home/janus/Downloads/zuluCrypt-master'
Linking C executable zuluCrypt-cli
cd /home/janus/Downloads/zuluCrypt-master/zuluCrypt-cli && /usr/bin/cmake -E cmake_link_script CMakeFiles/zuluCrypt-cli.dir/link.txt --verbose=1
/usr/bin/cc      -pie CMakeFiles/zuluCrypt-cli.dir/bin/main.c.o  -o zuluCrypt-cli -rdynamic libzuluCrypt-exe.so.1.2.0 libzuluCrypt.so.1.2.0 libStringList.a -lcryptsetup -lblkid ../external_libraries/tc-play/libtcplay.a libzuluCryptPluginManager.so.1.0.0 libString.a libProcess.a -pthread libSocket.a -Wl,-rpath,/home/janus/Downloads/zuluCrypt-master/zuluCrypt-cli: 
libzuluCrypt.so.1.2.0: undefined reference to `PKCS5_PBKDF2_HMAC'
libzuluCrypt.so.1.2.0: undefined reference to `OPENSSL_add_all_algorithms_noconf'
libzuluCrypt.so.1.2.0: undefined reference to `EVP_get_digestbyname'
collect2: error: ld returned 1 exit status
zuluCrypt-cli/CMakeFiles/zuluCrypt-cli.dir/build.make:95: recipe for target 'zuluCrypt-cli/zuluCrypt-cli' failed
make[2]: *** [zuluCrypt-cli/zuluCrypt-cli] Error 1
make[2]: Leaving directory '/home/janus/Downloads/zuluCrypt-master'
CMakeFiles/Makefile2:396: recipe for target 'zuluCrypt-cli/CMakeFiles/zuluCrypt-cli.dir/all' failed
make[1]: *** [zuluCrypt-cli/CMakeFiles/zuluCrypt-cli.dir/all] Error 2
make[1]: Leaving directory '/home/janus/Downloads/zuluCrypt-master'
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

Adding `-lcrypto` in `zuluCrypt-master/zuluCrypt-cli/CMakeLists.txt`  so that it says

```
 if( STATIC_TCPLAY )
        TARGET_LINK_LIBRARIES( zuluCrypt     String StringList Process ${cryptsetup_lib} ${blkid} -lcrypto tcplay-static )
 else()
        TARGET_LINK_LIBRARIES( zuluCrypt     String StringList Process ${cryptsetup_lib} ${blkid} -lcrypto ${TCPLAY_LIB} ${TCPLAY_LIBRARIES} )
 endif()
```

fixes the problem, but I don't think it's the correct solution. I guess find_library should be used?

**Comment by mhogomchungu** [comment]
libcrypt is a required requirement of zuluCrypt.

why dont you want to use libgcrypt? Its a system library and its probably already installed in your system and cryptsetup which as a required dependency of zuluCrypt also probably already depends on it.

Did you also change things in zuluCrypt build process to make it not depend on ligcrypt? the build process fails a lot here if i remove libcrypt

**Comment by ysangkok** [comment]
Sorry, I was mistaken, gcrypt is indeed needed.

I am on Ubuntu and when I run `cmake .` it first complains about blkid, so I install libblkid-dev, then cryptsetup, so I install libcryptsetup-dev, then libsecret, so I install libsecret-1-dev, then gcrypt, so I install libgcrypt20-dev. Now cmake succeeds, but the builds fails, because libdevmapper.h is missing. So I install libdevmapper-dev. Now the build gets to the error message shown above. Did I do anything wrong?

**Comment by mhogomchungu** [comment]
You are building from zuluCrypt-master.

There are instructions to build and install a zuluCrypt debian package and the instructions are located at "/debian_package_info/BUILD_INSTRUCTIONS"

The file is also here[1].

The 3rd step has a list of required packages.

I think it is better for you to build and install zuluCrypt using these instructions. Just copy each command and then paste them on the terminal to make sure you dont mistype them.

Will also appreciate if those steps works for you since you are using ubuntu while i tested them on debian jessie.

[1] https://raw.githubusercontent.com/mhogomchungu/zuluCrypt/master/debian_package_info/BUILD_INSTRUCTIONS

**Comment by mhogomchungu** [comment]
Also make sure you start with a clean build folder every time you correct or change a setting. You should always do this when building using cmake.

I think you were getting the error above because tcplay already registered that you did not have libgcrypt and it did not correct this when you installed libgcrypt and the problem would have corrected itself if you had started from a clean build after you installed libgcrypt.

**Comment by mhogomchungu** [comment]
I am closing this one since the above comment identified the problem you were having.

To be clear,the "wrong" thing you were doing was not starting with a clean build folder every time you added a dependency.

You should always start with a clean build folder everytime you change or tweak build settings.

Thanks for trying out zuluCrypt and feel free to add anything in this thread if anything else come up.

**Comment by ysangkok** [comment]
Thanks! I understand the issue and my mistake.
