### ISSUE TITLE
Failed to enable polkit support

### ISSUE THREAD

**Issue by git70** [mhogomchungu/zuluCrypt#161]
Hi Francis

Scenario:
1. Create => Encrypted Container In A Hard Drive
2. Selecting partitions on the disk /dev/sdb1
3. Question "Do You Want To Write Random Data To /dev/sdb1" ... => Yes
Error "Failed to Enable Polkit Support"

The second problem (perhaps related):
Manage System Volumes and Manage Non System Volumes (CTRL-C or CTRL-M) => No effect (nothing happens, nothing opens)

Checked for:
ZC 6.0.0
Linux Mint 19.3 and 20.1 (Ubuntu 18.04 and 20.04)

Please help....

Edit:
The above problem does not occur on USB pendrive.
Applies only to hard drives connected to SATA or USB adapter.

**Comment by mhogomchungu** [comment]
Sorry for a long wait, i must have missed this one somehow.

1. Did you build zuluCrypt from source or are you using a version from your distribution?
2. Do you get a polkit prompt when zuluCrypt starts and no errors after you enter the correct password on the prompt?

**Comment by git70** [comment]
Hi Francis! Seen you back!

1. Version 6.0.0 from this github
2. No polkit prompt. Never

**Comment by mhogomchungu** [comment]
Is polkit working in your computer? Open the terminal and run ```pkexec ls``` and observe is you get a polkit prompt or not.

In zuluCrypt menu, click options and then click "manage system volumes" and observe if you are getting a polkit prompt.

**Comment by git70** [comment]
1. Yes, pkexec ls it works. The prompt polkit appears.
2. Francis... read exactly my first post -> Manage System Volumes and Manage Non System Volumes (Ctrl-C or CTRL-M) => No Effect (Nothing Happens, Nothing Open)

**Comment by git70** [comment]
I noticed one more thing:
At LiveCD/USB Linux Mint 20.1, problems do not occur. 
WTF?

**Comment by mhogomchungu** [comment]
The problem goes away if :- 
1. zuluCrypt-gui is run from root's account and i suspect this is how zuluCrypt-gui is run from the livecd.
2. zuluCrypt-gui is run from a normal account and the account is a member of group "zulucrypt".
3. zuluCrypt-gui is run from a normal account and the partition to be operated on is not identified as a "system partition". A system partition is defined as a partition that is on a drive that sits inside a computer. By this definition,a USB pendrive is a not a system partition because it is outside of a computer. If your SATA hard drive is external then it is wrongly identified by your system and you can correct it by following instructions from here[1]

[1] https://wiki.archlinux.org/index.php/udev#Some_devices,_that_should_be_treated_as_removable,_are_not

**Comment by mhogomchungu** [comment]
This is now fixed and you can get binary packages from here: https://download.opensuse.org/repositories/home:/obs_mhogomchungu/
