### ISSUE TITLE
To long timeout when wrong password is entered for Veracrypt partitions

### ISSUE THREAD

**Issue by HypnoticST8** [mhogomchungu/zuluCrypt#167]
Hello

When wrong password is entered it's usually takes about two minutes to show the massage that partition can't be mounted.
That's definitely too long. There is also minor bug with the timer when seconds pass value of 59 (1 min 61 sec instead od 2 min 1 sec). I'm using zuluCrypt 5.7.1 on Debian based system.

**Comment by mhogomchungu** [comment]
VeraCrypt volumes are designed to be very annoying when a wrong password is entered because it has too many crypto properties and all need to be tried before giving up and the whole things takes too much time.

Recent versions of cryptsetup has ability to specify what crypto options to use to unlock a VeraCrypt volume and this considerably reduces the times it to get a wrong password error because only one option is tried.

**Comment by HypnoticST8** [comment]
I haven't changed any options when mounting mentioned volume but upgraded to version 6.0.0 which seems to fix the issue.
No i takes about 20 seconds instead of two minutes.

**Comment by mhogomchungu** [comment]
Older versions of zuluCrypt used tcplay to unlock TrueCrypt/VeraCrypt volumes and recent versions now use cryptsetup and i suspect the switch to cryptsetup is the cause of the improvement you see.

Thanks for the update.
