### ISSUE TITLE
favorites settings not saved

### ISSUE THREAD

**Issue by HypnoticST8** [mhogomchungu/zuluCrypt#186]
Hello

I don't know if it's intended behavior but settings for favorites are not saved. This happens regardless if there are any entries in 'favorites list' tab. The attached link to the video show the problem. I'm using MX Linux that is based on Debian.
https://we.tl/t-lydeQgXTdy

**Comment by mhogomchungu** [comment]
What version of zuluCrypt are you using?

**Comment by HypnoticST8** [comment]
Ops, sorry about that. The version is 6.1.0, recently upgraded from 5.7.1-2 but I don't know if the bug was present in that version since I never enter that options.

**Comment by mhogomchungu** [comment]
It is a known problem and is related to this[1] bug report and the explanation for the bug is here[2] in the changelog.

I will make a new release hopefully tomorrow or later on today.

[1] https://github.com/mhogomchungu/zuluCrypt/issues/182
[2] https://github.com/mhogomchungu/zuluCrypt/blob/c2620ade6859b6a282cc33fc186ee2697c2cb3c7/changelog#L340

**Comment by mhogomchungu** [comment]
New version is out and it has a fix for this issue

https://github.com/mhogomchungu/zuluCrypt/releases/tag/6.2.0
