### ISSUE TITLE
Is zuluCrypt "really" supporting Hidden Veracrypt Volumes up to AND even larger then 16TB using drives that only have a 512 bytes sector?

### ISSUE THREAD

**Issue by DLLDev** [mhogomchungu/zuluCrypt#196]
Regarding Veracrypt this should (for weird reasons) not be possible.
The cap. seems to be 16TB and the sector size of the drive must be 4096 bytes.

[Image](https://i.stack.imgur.com/Lqr4g.png)

But, i´ve just created a RAID0 array using 4x 8TB SSDs with a physical sector size of 512 bytes (Sector size (logical/physical): 512 bytes / 512 bytes),
then used zuluCrypt instead of Veracrypt to create the hidden volume with even more then 16TB with EXT4 and it worked.

Now im wondering why it works and if it really works or if i have to expect heavy issues and data loss using the encrypted array.

**Comment by mhogomchungu** [comment]
TrueCrypt and VeraCrypt volumes are created using [tcplay](https://github.com/bwalex/tc-play) project. These volumes are unlocked using [cryptsetup](https://gitlab.com/cryptsetup/cryptsetup).

When creating a volume, tcplay first creates it and then immediately cryptsetup unlocks it for zuluCrypt to put a file system in it using mkfs tool. 

Best place to ask your question is with cryptsetup project since they are the ones who unlocks it and manages it. It should be a bug if it unlocks it and fails to use it as expected.

Sorry for a late reply, i saw it, said i will reply later and somehow forgot about it.
