### ISSUE TITLE
zuluCrypt-cli tests fail at "create a luks type volume using a key: FAILED"

### ISSUE THREAD

**Issue by doktor5000** [mhogomchungu/zuluCrypt#27]
Hi,

when trying to build a Mageia package for zulucrypt, I noticed that the tests run by `zuluCrypt-cli --test` seem to fail during the package build on our development branch.  

They work fine on our stable release where I tested first, and I don't really understand why the tests fail. Only difference seems to be that I needed to use LD_LIBRARY_PATH to point to the libraries.

For the tests themselves, from what I can see, it tries to create [two keyfiles](https://github.com/mhogomchungu/zuluCrypt/blob/master/zuluCrypt-cli/bin/test.c#L61) `/tmp/zuluCrypt-KeyFile` and `/tmp/zuluCrypt-KeyFile1` and fails after that when creating a LUKS volume:

```
+ LD_LIBRARY_PATH=/home/user/rpmbuild/BUILDROOT/zulucrypt-4.8.0-1.mga6.x86_64/usr/lib64
+ build/zuluCrypt-cli/zuluCrypt-cli --test
creating a testing image file
creating a testing image file
creating a testing image file
creating a keyfile
creating a keyfile

create a luks type volume using a key: FAILED
error: Bad exit status from /home/user/rpmbuild/BUILDROOT/rpm-tmp.yQVXYU (%check)
```

When trying to manually run the test as mentioned in #18 it fails this way:

```
LD_LIBRARY_PATH=/home/user/rpmbuild/BUILDROOT/zulucrypt-4.8.0-1.mga6.x86_64/usr/lib64 ./zuluCrypt-cli -ck -d test.img -t tcrypt -p xxx
ERROR: setgroups() failed: Operation not permitted
```

**Comment by doktor5000** [comment]
Just tested again with the installed package, and all tests complete without issues. Could this be related in any way to the LD_LIBRARY_PATH?

This is the output of the tests from the installed packages:

```
[user@openqa_mga6]─[15:49:18]─[~] zuluCrypt-cli --test
creating a testing image file
creating a testing image file
creating a testing image file
creating a keyfile
creating a keyfile

create a luks type volume using a key: PASSED

check if a luks volume is a luks volume: PASSED

create luks header backup: PASSED

restore luks header from backup: PASSED

create a plain type volume using a key: PASSED

create a tcrypt type volume using a key: PASSED

open a plain volume with a key: PASSED
closing a plain volume: PASSED

open a plain volume with a keyfile: PASSED
closing a plain volume: PASSED

open a tcrypt volume with a key: PASSED
closing a tcrypt volume: PASSED

open a plain volume using a plugin: PASSED
closing a plain volume: PASSED

open a luks volume with a key: PASSED
closing a luks volume: PASSED

open a luks volume with a keyfile: PASSED
closing a luks volume: PASSED

open a luks volume using a plugin: PASSED
closing a luks volume: PASSED

check key slots in use: 30000000

add a key to a luks volume using a key and a key: PASSED
add key to luks volume using keyfile and keyfile: PASSED
add key to luks volume using passphrase and keyfile: PASSED
add key to luks volume using keyfile and passphrase: PASSED

check key slots in use: 11111000

remove a key from a luks volume using a key: PASSED
remove a key from a luks volume using a keyfile: PASSED
check key slots in use: 01011000

check if there are no opened mappers: PASSED
```

**Comment by mhogomchungu** [comment]
dm-crypt in an infrastructure in the linux kernel that deals with block device encryption.

zuluCrypt,TrueCrypt,VeraCrypt,cryptsetup,tcplay among others use it as a backend when encrypting/decrypting user data.

This backed(dm-crypt) requires its front ends to be root privileged when invoked and zuluCrypt gains root privilege by configuring zuluCrypt-cli and zuluMount-cli as suid-root.

The test succeeds with your installed package because zuluCrypt-cli binary has 4755 permissions and the test fails in your development branch probably because of wrong permissions(it probably has 0755 permissions).In your development branch,the test should succeed if run from root's account.

TrueCrypt and VeraCrypt gains root's privileges by invoking "sudo" and dm-crypt backend is called after privileges are elevated when sudo succeeds.

udisks gains root's privileges by having its backend started from root's account as part of the boot up process.

cryptsetup and tcplay just requires to be run from root's account and they arent very user friendly because of this.

**Comment by mhogomchungu** [comment]
I am closing this one since i think i have answered your question but dont hesitate to respond if anything isnt clear.

There will be a new version of zuluCrypt released tomorrow,march 1st,2016.

**Comment by doktor5000** [comment]
@mhogomchungu No problem, now that you mention the suid bit it makes sense :)
