### ISSUE TITLE
Feature request: make bind mountpoint (public mirror) configurable

### ISSUE THREAD

**Issue by pspot2** [mhogomchungu/zuluCrypt#31]
Hi Francis,

when selecting the public mirror in zuluMount, currently the second mountpoint is created under "/run/media/public". Would it be possible to make it changeable from the GUI if necessary (e.g. when the checkbox is ticked, an editable field appears, containing the default value)?

The reason I'm asking is that it would be the most elegant solution to having the (S)FTP-chrooted users access volumes unlocked by zuluCrypt. As symlinks don't work in this kind of setup, one has to bind-mount zuluCrypt's public mountpoint once again as root to a directory inside the chrooted one.

Also, the only way to mount the public mirror from GUI is using zuluMount. I usually use zuluCrypt because it allows me to select VeraCrypt volumes from the menu. Mounting VC from zuluMount is more awkward - you need to additionally set the volume to VC in the unlock dialog box. Would it be possible to copy the public mirror functionality to zuluCrypt's unlock dialog box as well?

Thanks.

**Comment by mhogomchungu** [comment]
From a technical point of view,having users freely choose shared mount point has two problems.

1. The current logic says, "with a mount path of foo/xyz,check if it has a shared mount point by checking if /run/media/public/xyz path exists". Making the shared mount point being at arbitrary location will complicate the logic and will probably involve parsing "/proc/self/mountinfo" looking for bind mounts.

2. For security reasons,it is not wise for a normal user to have writing access on the mount point prefix path so allowing users to set shared mount point to arbitrary locations is a bad idea. I can add a compile time option to change the shared mount point prefix if that will be workable for you.Predictable path prefix is most important here to simplify code logic.

GUI elements are complicated as they are and i do not want to add more elements unless its something really important/very fundamental or something most users will expect as default. Very few people will use share mount point feature and fewer among them will want to chang it and hence i think its a good idea to have a GUI element for it.

I did not add the shared mount point feature to zuluCrypt-gui because i run out of letters for zuluCrypt-cli options and reusing existing letters adds to confusion. Will look at them again to see if there is any available i can use to support the feature.

**Comment by mhogomchungu** [comment]
This commit[1] makes it less awkward to select a volume as a VeraCrypt volume in zuluMount-gui as it adds a checkbox in the main UI under "Share Mount Point" checkbox.

I can also add ability to have the choice remembered between invocations of the dialog box if you want.

Selecting a VeraCrypt volume in zuluMount-gui is better supported and it can also works with the favorite feature.

[1] https://github.com/mhogomchungu/zuluCrypt/commit/035b6c41f4c2e6682f321f9e65ee5cd5412286fd

**Comment by pspot2** [comment]
> I can also add ability to have the choice remembered between invocations of the dialog box if you want.

Yes please. Thank you.

As for the public mirror:

- not all elements of "/run/media/public/xyz" are owned by root and not writable by anyone else (which is mandated by - for example - SSHd for chrooting), therefore I cannot chroot the user into that path directly.

- a symlink to that path will also not work if I chroot the user to his homedir, as the path is located above the chrooted homedir in the FS hierarchy.

I guess my alternatives here are:

1) Open that volume as root using cryptsetup directly during the boot process. I could then chroot the user into it directly.

2) Use zuluMount, but then additionally bind-mount the public path into user's chrooted homedir.

**Comment by mhogomchungu** [comment]
```"/run/media/public/``` is what i call ```shared path mount point prefix```.

```/run/media/private/``` is what i called ```mount point prefix```

All components of these two prefixes are supposed to be owned by root and normal users
are supposed to not have write access to them.

``````/run/media/private/$USER``` path is supposed to be accessible only by $USER without writing access,only reading and executing.

What is an example of a shared mount point path prefix that will work "out of the box" with zuluMount in your scenario.

Another commit[2] and zuluMount-gui now remembers the option to assume a volume about to be mounted is a veracrypt volume.

Do you get any warnings when building from git,i changed a compiler option to remove warnings i was getting and i am not sure if i caused other warnings to be generated.

[2] https://github.com/mhogomchungu/zuluCrypt/commit/1b5fbc3943042340e93f2d9e9b962c5f59ab82cc

**Comment by mhogomchungu** [comment]
I am closing this one as "fixed".

Previous commits mentioned in my previous comments makes it possible to set zuluMount-gui to remember the veracrypt option and hence you can use zuluMount-gui as a veracrypt volume unlocker with no awkwardness or additional clicks.

A commit[1] i just made makes it possible to change the default share mount point prefix to any path of your preference. To change the default path,rebuild zuluCrypt from git with the following additional option: ```-DSHARE_MOUNT_PREFIX=/your/prefered/path```.

I am closing the bug report but feel free to commit if you have anything in your mind.

[1] https://github.com/mhogomchungu/zuluCrypt/commit/e72ca5a3304de8b272a83bc6ec27f5604fbfec77

**Comment by pspot2** [comment]
I think this should do it. Thank you.

**Comment by mhogomchungu** [comment]
zuluCrypt-gui now has a public mount point functionality.

The option to set a volume as a veracrypt volume is removed from the menu and placed in the password dialog box.This option is also remembered like in zuluMount-gui. The old behavior you were using was broken when using the favorites feature.

These recent changes means you can go back to using zuluCrypt-gui to get the abilities you wanted.
