### ISSUE TITLE
Does not recognize existing group membership of user "zulucrypt"

### ISSUE THREAD

**Issue by xenongit** [mhogomchungu/zuluCrypt#32]
When trying to encrypt a system partition and trying to make a backup of the header, zuluCrypt gave the response: cannot do it, you have to be a member of group zulucrypt. However, the active user *was* and is a member of this group on my Linux machine. I verified this several times. (First I created the group in the systems group administration, then I added the user in the user administration.)

See attached screenshot (*jpg).
![zuluerror](https://cloud.githubusercontent.com/assets/18113926/14076368/52b1cd16-f4e1-11e5-8b3f-bed6536f3a14.jpg)

System: 
Linux Mint 17.3 Cinnamon 64-bit, based on Ubuntu 14.04
Cinnamon-Version 2.8.7
Linux-Kernel 3.19.0-32-generic

I finally did the task by opening zuluCrypt as root-user, but that has its own drawbacks. It would be nice it would work by recognizing the group membership.
I like zuluCrypt so far; thank you!

**Comment by mhogomchungu** [comment]
run the following command from your user account and paste its output

```
id
```

**Comment by xenongit** [comment]
mhogomchungu, thank you for your prompt reply! This is the output of the command id:

uid=1000(wolfgang) gid=1000(wolfgang) Gruppen=1000(wolfgang),4(adm),6(disk),24(cdrom),27(sudo),30(dip),46(plugdev),107(lpadmin),110(sambashare),124(vboxusers),1001(zulucrypt)

xenongit

**Comment by mhogomchungu** [comment]
You just noticed a bug and i just fixed it[1].

If you build from source then build from git version to have the fix.

If you used binary packages i provide,then uninstall them first and then install the git binary packages from here[2].

I am closing this bug report as being "fixed" but will appreciate if you could test and confirm the bug is gone.

[1] https://github.com/mhogomchungu/zuluCrypt/commit/1b573bc6107d5706696ade025bb117a290445a80

[2] http://download.opensuse.org/repositories/home:/mhogomchungu/xUbuntu_14.04/

**Comment by xenongit** [comment]
Thank you! That was quick.
I'll certainly test it and I will give you feedback; I'll do it in the next 
couple of days.

Xenongit

Am 28.03.2016 um 18:24 schrieb mhogomchungu:
