### ISSUE TITLE
Ubuntu 16.04 problems

### ISSUE THREAD

**Issue by Baka9k** [mhogomchungu/zuluCrypt#43]
I successfully used zuluCrypt and zuluMount on Xubuntu 14, but after updating to Ubuntu 16.04 I can't use it.

I have installed zuluCrypt and zuluMount from ubuntu archives, then removed them and installed from `ppa:hda-me/zulucrypt`, but both versions work the same way: if I try to open container in a file with zuluCrypt, it says `volume could not be opened with presented key` (I am absolutely sure in the correctness of the key), and if I try to mount it with zuluMount, zuluMount window becoming disabled (gray) when I enter the key and press Open button and remains in this state. Folder with container name appears in /run/media/private/username/, but it's empty.

I tried to install it from source, but did not understand how to install the required libraries:
`E: Unable to locate package libdevmapper-devel`
`E: Unable to locate package kde-devel`
`E: Unable to locate package libsecret-devel`
`E: Unable to locate package libgcrypt-devel`
`E: Unable to locate package cryptsetup-devel`
`E: Unable to locate package gcc-c+`
`E: Couldn't find any package by regex 'gcc-c+'`
`E: Unable to locate package libqt4-devel`
`E: Unable to locate package libblkid-devel`
`E: Unable to locate package libpwquality-devel`

Does zuluCrypt work on Ubuntu 16.04, or I doing something wrong?

**Comment by mhogomchungu** [comment]
uninstall the versions you have installed and then install the 16.04 package from a link on the front page of the project located at: http://mhogomchungu.github.io/zuluCrypt/ and try again.

i have ubuntu 16.04 and it works fine here,but will check again shortly to confirm

**Comment by mhogomchungu** [comment]
is your volume a LUKS volume,or a TrueCrypt volume or a VeraCrypt volume?

Have you tried alternative tools to open your volume? The problem  could be one of the folloing

1. The volume has a corrupt header.
2. You dont remember the password as well as you think you do.
3. The volume is now on a path that uses at least one accented characters. French user reported a problem when trying to unlock a volume that uses a french accented character a while ago but i could not reproduce the problem locally.

**Comment by Baka9k** [comment]
Thanks for the quick response!

I just removed all my zulu* packages and ppa, rebooted ubuntu and then downloaded zuluCrypt-5.0.0-ubuntu-16.04-Xenial_Xerus.tar.xz and installed all packages for amd64. 
Then I tried mount my volume with zuluMount, but after entering key and clicking Open nothing happens for several minutes, and volume folder in /run/media/private is empty.

![screenshot from 2016-08-04 18-01-07](https://cloud.githubusercontent.com/assets/12223917/17406820/ae0209a0-5a6d-11e6-81f1-e8d54bd4fc94.png)

![screenshot from 2016-08-04 18-01-17](https://cloud.githubusercontent.com/assets/12223917/17406827/b7d74562-5a6d-11e6-9979-63674ff1517f.png)

I think password is right, because when I type wrong password, I immediately get the message about this, and the volume folder in /run/media/private do not appears at all.

My volume is on ntfs drive, and path contains English letters only.

My volume is LUKS volume.

I will try to open it in other ways, and then I will write here about the progress.

**Comment by mhogomchungu** [comment]
Your images shows nothing is wrong.

What is the output of the following command

zuluCrypt-cli --test

**Comment by Baka9k** [comment]
`WARNING: "loop" kernel module does not appear to be loaded,
tests and opening of encrypted containers in files will fail if the module was not built into the kernel`
But all tests are passed.
So I think the problem is in my volume file or path, not in zuluMount. 
Thanks for help and sorry for disturbing you.

**Comment by mhogomchungu** [comment]
It makes no sense why its not working for you and i would like to know the reason because the same problem is bound to happen to somebody else if it hasnt happened already..

Does it also not work with zuluCrypt-gui?

You said the volume is on an ntfs volume,can you copy it to your home directory and try to access it from there?

**Comment by Baka9k** [comment]
I have installed cryptsetup and successfully opened my volume with it. I also created a test volume using zuluCrypt and successfully opened it in zuluMount. Then I tried again to open my volume with zuzuMount, and I did it! I do not know what I did (maybe change something in /dev/), but now I can mount my volume. I used the same password on all my attempts, and same volume file path.

**Comment by mhogomchungu** [comment]
Well,i dont know what the problem was but i am glad its gone.

Atleast something good came out it this,you are now using my debian packages and hence the project's GUI applications now start without prompting for a root password :-)

**Comment by Baka9k** [comment]
Yes! Thank you for your awesome program.

**Comment by fabiansinz** [comment]
I just want to add to this issue, because the steps described by @Baka9k helped me resolve it. I had exactly the same problem only with a luks file container. But when I opened it with cryptsetup it worked. Afterwards I was also able to open it with the zuluCrypt-gui. I did a `modprobe loop max_loop=255` somewhere along the way as well. I have no idea what fixed it, but now it works. Maybe that will help other people resolve the problem.

**Comment by mhogomchungu** [comment]
I think i found the problem,i always suspected the problem is most likely where a loop device is attached to an image file and i looked at the code just now and saw and fixed a bug.

If you guys know C code,first there is a new[1] was of doing it and old[2] was of doing it. zuluCrypt tries the new way and falls back to the old way when the new way fails and the old way had a "use memory after it was deleted" bug which causes an undefined behavior. Things just fails on my system but it leads to a hang in you guys system.

 cryptsetup does it the same exact way and i new cryptsetup should have the same problem if i it it correctly and that gave me clue. I think following around a bit caused the new way to start working again hiding the bug in the old way.

The git version has the fix already and you can get binary packages with the fix from here:
http://download.opensuse.org/repositories/home:/mhogomchungu/

[1] https://github.com/mhogomchungu/zuluCrypt/blob/142173c8dcd8b66c7f028445f3688ed1f721ad25/zuluCrypt-cli/lib/create_loop_device.c#L275

[2] https://github.com/mhogomchungu/zuluCrypt/blob/142173c8dcd8b66c7f028445f3688ed1f721ad25/zuluCrypt-cli/lib/create_loop_device.c#L275

[3] https://gitlab.com/cryptsetup/cryptsetup/blob/master/lib/utils_loop.c
