### ISSUE TITLE
Text scales over the borders

### ISSUE THREAD

**Issue by somniumAeternam** [mhogomchungu/zuluCrypt#44]
Hallo! I've just tried zulucrypt and it works really well. But on my desktop and mobile computer I use a higher font dpi in plasma 5 desktop. All Qt applications work fine, but in zuluCrypt the text is to big, or the ui is not scaling according to the text. I attached a screenshot which illustrates the problem further. It is present through the whole program. I'm using Arch Linux and zulucrypt 5.0.0-1 from AUR.

![spectacle tj3162](https://cloud.githubusercontent.com/assets/9334916/17927602/b96c7a26-69f6-11e6-8ef8-a757750b61de.png)

**Comment by mhogomchungu** [comment]
Yes,font sizes is a problem since most ui elements arent scalable and i will revisit this problem at some point in the near future.

In the mean time,have you tried to use smaller fonts? You can set font sizes and types by going to "menu->options->select font". This was my work around for the font scaling issue

**Comment by pspot2** [comment]
Another vote for this request. I cannot make the font smaller because I'm using my flatscreen TV as a monitor and sit around 5 meters away from it.

**Comment by mhogomchungu** [comment]
Trying to solve this problem now and will appreciate some help.

The functionality only works with Qt5 build using atleast version 5.6.0 of Qt5.

After you have the project build and installed,run zuluCrypt and a config file at
```~/.zuluCrypt/zuluCrypt.scaleFactor``` will be created,open the text file,change the number to
your preferred number and then restart zuluCrypt and the GUI will now be bigger/smaller depending on the number you choose. 

The default value is 1 and it seems to give the current GUI size,a value of two will double the GUI and a decimal number(like 0.8) will shrink it.

Will add a GUI way to change the value if this works.

**Comment by mhogomchungu** [comment]
I think this one is solve.

Add a comment if not and i'll reopen it.

**Comment by pspot2** [comment]
Attaching a screenshot of how the unlock window looks like on my setup. The font size is too large, but I cannot decrease it because I sit 5m away from the TV and the font has to be big. The GUI elements should scale instead.

![screenshot_20180211_031240](https://user-images.githubusercontent.com/14319777/36068624-bb49bee2-0ed9-11e8-910e-a9126d376486.png)

**Comment by mhogomchungu** [comment]
look for ```ScaleFactor``` entry in ~/.config/zuluCrypt/zuluCrypt.conf" and change it to a different value, restart and see if it will make a difference.

You must be using Qt5 build for this option to have an effect

**Comment by pspot2** [comment]
Tried this suggestion. What this setting does is scale _all_ elements proportionally, e.g. both text and fields, leading to exactly the same effect that text doesn't fit the fields. In other words, it works like a zoom that zooms everything. What we need is the auto-scaling of field and button sizes depending on the font size chosen. It seems to be a standard Qt feature, e.g. all other KDE apps do this properly. Just try to increase the global font size and launch any other application to check.

**Comment by mhogomchungu** [comment]
Do you see the same problem with the main window?
