### ISSUE TITLE
Fedora packages

### ISSUE THREAD

**Issue by rapgro** [mhogomchungu/zuluCrypt#47]
Hi,
I hereby proudly inform about official packages in the Fedora and in EPEL7 stable repositories, as you may already know. It's now sufficient to just call as root without any additional repository needed:
`dnf install zulucrypt`
Please be aware that the packages are not yet in Fedora 23 but requested.

**Comment by mhogomchungu** [comment]
Thank you very much.

I googled a bit and came to this page[1]. Is this link "stable" in a sense that i can add it to the project's front page so that Fedora users can quickly know if there are official packages of zuluCrypt for the version of Fedora they are using?.

https://admin.fedoraproject.org/pkgdb/package/rpms/zulucrypt/

**Comment by rapgro** [comment]
Yes.

**Comment by mhogomchungu** [comment]
Just made a comment on the front page about availability of official Fedora packages of zuluCrypt.
