### ISSUE TITLE
File volume unopenable after OS reinstall

### ISSUE THREAD

**Issue by esotericDisciple** [mhogomchungu/zuluCrypt#50]
I had a couple volumes inside a home folder for a fedora 24 operating system, but I had to re-install fedora when the last update broke the nvidia drivers, and I switched out hard drives in the meantime since I wanted more capacity than what the one holding the zulucrypt volumes had. I re-connected that drive externally, but zulucrypt now complains that my password isn't correct, both for the volume and for the header backup! Oh, and I set up home for the new fedora instillation to be encrypted (using LUKS) by default...

**Comment by mhogomchungu** [comment]
use zuluCrypt to create a test volume,does it still work?

is your volume a LUKS,VeraCrypt or TrueCrypt volume?

**Comment by esotericDisciple** [comment]
I think they are truecrypt volumes...

**Comment by esotericDisciple** [comment]
Creating test volume doesn't work, either. It doesn't accept the password I used for it...

**Comment by esotericDisciple** [comment]
Never mind the last comment turns out I mistyped the test volume, but I still can't get into the ones on the other hard drive...

**Comment by mhogomchungu** [comment]
Are you using the packages i provide on the project's front page or the ones provided by fedora?

Try to use cryptsetup directly/TrueCrypt/VeraCrypt to see if it can unlock the volume. I think this is the only way to be sure the problem is in zuluCrypt.

**Comment by esotericDisciple** [comment]
Ah, it seems that the device(s) couldn't be opened/mounted because there wasn't any exfat library installed on the newer system. I had forgotten what format the device(s) had. The error message in zuluCrypt is really misleading, though...

**Comment by mhogomchungu** [comment]
Git version will print below error when a file system is not supported.

```
ERROR: Failed to mount a filesystem:invalid/unsupported mount option or unsupported file system encountered
```

**Comment by esotericDisciple** [comment]
Thanks, I look forward to that when it makes Fedora's official repos!

**Comment by mhogomchungu** [comment]
Latest version of zuluCrypt(5.0.2) was released december first,2016 and its only a matter of time before fedora picks it up.

I do provide fedora packages and links are on the project's front page. The biggest difference between my packages and official fedora packages are:

1. GUI components from my package "just works",you will get a polkit prompt with fedora packages requiring you to enter root's password. The GUI components will also most likely look different because they will be running from root's account..

2. CLI components from my package "just works" from normal user account,they dont in fedora provided packages.
