### ISSUE TITLE
Hidden folders starting . (dot)

### ISSUE THREAD

**Issue by Madji** [mhogomchungu/zuluCrypt#54]
![_2017-01-17_15-44](https://cloud.githubusercontent.com/assets/2238714/22021214/61155b70-dcd5-11e6-844b-a257ce5cb264.png)

the application does not see folders beginning with a dot. for example, my container is in the folder and I can not edit it. may be I something not so do?
the path is mounted manually in console . and it appears.
![_2017-01-17_15-44-09](https://cloud.githubusercontent.com/assets/2238714/22021140/087a0d12-dcd5-11e6-9712-adf55c1e76d9.png)

**Comment by mhogomchungu** [comment]
The problem is not with zuluMount but with that folder dialog box not showing hidden folders by default. There should be an option in that folder dialog box to show hidden folders(folders that starts with a dot), activate the option and your encrypted hidden folder will show up on the list.

That folder dialog box does not belong to zuluMount,it belongs to Qt/KDE and there is nothing i can do to manipulate it.

**Comment by mhogomchungu** [comment]
There is another project of mine called "SiriKali"[1] and its capable of creating and unlocking cryfs volumes among other folder based encrypted volumes. zuluMount can only unlock them.

[1] https://mhogomchungu.github.io/sirikali/

**Comment by Madji** [comment]
Thanks
