### ISSUE TITLE
[Homepage] some issues & improvements

### ISSUE THREAD

**Issue by DJCrashdummy** [mhogomchungu/zuluCrypt#59]
- [x] the VeraCrypt-link is dead, since CodePlex is shutting down and VeraCrypt has a new home: https://www.veracrypt.fr/en/Home.html

- [x] if i got it right, VeraCrypt is no longer based on tcplay but on zuluplay, so i think this should be mentioned...

- [ ] at the section _Binary packages for debian and ubuntu_ it should be mentioned that `zulucrypt-cli` & `zulucrypt-gui` as well as `zulumount-cli` & `zulumount-gui` is available via the repositories since _stretch (9.0)_ or _xenial (16.04LTS)_.

- [x] a bunch of typos with missing and also too much `spaces` are sprinkled on the whole page.

**Comment by mhogomchungu** [comment]
The current front page now has a correct link to veracrypt project home page. Thanks for the info about the dead previous link.

The current front page now refers to zuluplay instead of tcplay.

At the moment, i do not want to link to those packages in debian/ubuntu/fedora because they are build in a way that does not give an experience i want users of zuluCrypt to have. I will add them when i have released version 5.2.0 since GUI components in this version in those mentioned distros will behave like in packages i provide. The CLI components will be just as "broken" but i can live with that one.

Too much spaces are due to how github renders pages or maybe i dont know how to do it right. Breaking a line with a new line character causes github page renderer to ignore the new line and not breaking a line.Using two lines to break a line causes the page renderer to display the empty line between two lines as it is seen in the page. I am all ears if you improve this.

You will have to mention the typos because I just read the whole page and did not see any.

**Comment by DJCrashdummy** [comment]
@mhogomchungu: thanks for the quick response!

> ...i do not want to link to those packages in debian/ubuntu/**fedora**...

ok, but fedora packages are already mentioned:
> zuluCrypt packages are in Fedora repositories and can be installed through normal/standard package installation procedures in Fedora.

---

so if i got you right, you will backport version 5.2.0 for stretch (9.0) or xenial (16.04LTS) and newer via repositories?

> The CLI components will be just as "broken" but i can live with that one.

i'm not sure what you want to tell with this one...? - _i'm hardly using zuluCrypt, so i'm not so familiar with the project._

---

i took me some time to find, but i did... and so i took a look at the `index.md` and corrected some things, see https://github.com/mhogomchungu/zuluCrypt/pull/60. hopefully i've done everything right and it is displayed correct, because am neither a github-pro; i signed in just a little bit more than a month ago.

**Comment by mhogomchungu** [comment]
> ok, but fedora packages are already mentioned:

I guess i will add a comment or two about debian/ubuntu to be fair.

The biggest difference between packages i provide for debian/ubuntu and packages that are in these distribution repositories is discussed here[1].

If you use zuluCrypt from debian/ubuntu repositories,you will notice a polkit prompt that asks for root's password when you start zuluCrypt-gui and zuluMount-gui. This is not very good UI experience and it also means the applications can not be by people who do not know root's password. The UI also looks foreign because it runs from root's account. The CLI components are also totally not usable from a normal user account because they require root's privileges to run..

With a bit of polkit magic,version 5.2.0 of zuluCrypt will remove the polkit prompt in these distributions but this is only for the GUI components. The CLI components will still be not usable from normal user account because they will still require root's privileges.

The above is why i do not like packages of my projects as created by Fedora,debian and ubuntu and why i will always continue to offer packages that are build they way i want my project to be used.

I have been thinking for a while now to add what is in the first couple of sentences in this page[1] in the main page. I think i will add them when i add comments about packages in debian/ubuntu repositories.

[1] https://github.com/mhogomchungu/zuluCrypt/issues/4
[2] https://github.com/mhogomchungu/zuluCrypt/wiki/zuluCryt-cli-howto

**Comment by DJCrashdummy** [comment]
> I guess i will add a comment or two about debian/ubuntu to be fair.

it's totally up to you! - i just wanted to point out, if you don't want to mention any of the debian/ubuntu/fedora-repositories for know, you have to remove the note about fedora.

---

oh, i didn't notice that the packages from the repositories requires root-privileges. that's truly "not so good"!
ok, thank you! now i've got the differences between the CLI and GUI.

---

> I have been thinking for a while now to add what is in the first couple of sentences in this page[**2**] in the main page.

yes, i think this is a good idea (beside fixing these packages)!

**Comment by mhogomchungu** [comment]
Closing this one as i think all the issues are now solved.

The main project page now also mentions that zuluCrypt is available in ubuntu and debian repositories.

Version 5.2.0 of zuluCrypt was released today. The polkit prompt will still be there in fedora,ubuntu,debian packages are provided by these distributions.

**Comment by gloomy-ghost** [comment]
FWIW, Debian seems to have fixed the zulupolkit issue, though I haven't upgraded to bullseyes (the testing branch) to test it. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910410

**Comment by mhogomchungu** [comment]
zuluCrypt always use zulupolkit when it needs elevated privileges.

There are two differences between my package and debian package.

1. When running GUI components, debian package unconditionally runs zulupolkit at startup while mine does it only on "dangerous" operations like trying to create a volume in a so called "system partition" or when zuluMount tries to mount an unencrypted system partition. One way to totally suppress the polkit prompt in my packages is to create and add your user to "zulucrypt" and "zulumount" groups.

2. CLI components in my package run from normal user account and from root account in the debian package. This difference is the main reason why zulupolkit exists.

According this this[1] patch, you will still get the prompt, but it will require user password and not root's password and this is a very, very, very big improvement and i am very happy with it. From some users i have heard from, zuluCrypt generating polkit prompt that require root's password was a big no-no for them because they didn't want to share the root password with all users of the computer and this debian change will make zuluCrypt acceptable to them.

If debian end up packaging zuluCrypt the way i prefer, will i stop distributing mine? This is a though one now because my packages allows users of old versions of debian and ubuntu to use the most updated versions of zuluCrypt without compiling it from source.

For example, according to download statistics of version 5.6.0 of my packages, ubuntu 18.04 is the most popular followed by ubuntu 19.04 and third place is ubuntu 16.04!! 17.04 and 17.10 are the least popular for some reason.

In debian, the most popular is debian 10 followed by 9 and 8 is the last one.

I think i will contrinue to distribute my packages from now on primarily to allow users of old ubuntu and debian to run upto date version.

[1]https://salsa.debian.org/debian/zulucrypt/blob/6fd86714791e0f3ab1275e279ce5d28668c45938/patches/fix_zulupolkit_policy.patch
