### ISSUE TITLE
association

### ISSUE THREAD

**Issue by peekaa** [mhogomchungu/zuluCrypt#65]
When I doubleclick container there is possibility to associate extension tc with application. There are many app in the list but not zuluCrypt. How to do that? Thank you. 

Linux, debian testing (buster), zulu from offical debian repository 5.0.2-2.

**Comment by mhogomchungu** [comment]
Thats the functionality of your file manager, what file manager are you using? right click on your image file and then select "properties" and there should be an option on the generated dialog to add zuluCrypt to the list.

**Comment by peekaa** [comment]
In the generated dialog there is no Zulucrypt...
Gnome.


Dne 3.8.2017 v 10:02 mhogomchungu napsal(a):

**Comment by peekaa** [comment]
![snimek z 2017-08-03 10-12-45](https://user-images.githubusercontent.com/3026590/28912470-b69b36aa-7834-11e7-8325-17612a9d3c24.png)

**Comment by mhogomchungu** [comment]
It will be hard for me to help you further because i do not use GNOME(i use KDE) and i do not know how to add entries to the application list context menu in GNOME.

The easiest way to access your image file is to add it to zuluCrypt favorite list and access it from there.

You can access the favorites list by clicking menu->favorites->manage favorites.

**Comment by jdoe0** [comment]
I think the reason ZuluCrypt doesn't appear in the list is because the desktop file doesn't have anything set for `MimeType`. ZuluCrypt needs to register a mime type for TrueCrypt container during installation and list the associated mime type in to the desktop file. See https://developer.gnome.org/integration-guide/stable/mime.html.en for more details.

**Comment by mhogomchungu** [comment]
I just made a commit[1] that should solve the reported problem.

Can you build from git sources and test?

[1] https://github.com/mhogomchungu/zuluCrypt/commit/db5df48e1eb3835524b16cfa4a81b45f635df31c

**Comment by mhogomchungu** [comment]
I am closing this one because i think the reported problem is fixed. Feel free to still comment if anything comes up.
