### ISSUE TITLE
Build instructions regarding external zuluplay

### ISSUE THREAD

**Issue by Piraty** [mhogomchungu/zuluCrypt#66]
Hi mhogomchungu,

i have questions regarding zuluplay and your build instructions.

https://github.com/mhogomchungu/zuluCrypt/blob/0841a81a57d6563c69aafdba9beb4ee3cc28b9ab/BUILD_INSTRUCTIONS#L129-L131

the marked passage is not clear, can you improve language/meaning please?
Also the configure-output does not help, see below:

### build with DINTERNAL_ZULUPLAY=false
```
-- ---------------------------------------------------------------------------
-- internal version of zuluplay will be used to create and open TrueCrypt and VeraCrypt volumes.
-- internal version of zuluplay will be used to create and restore TrueCrypt volume headers.
-- creation and restoration of VeraCrypt volume headers is currently disabled.
-- ---------------------------------------------------------------------------
```

### build with DINTERNAL_ZULUPLAY=true
```
-- ---------------------------------------------------------------------------
-- internal version of zuluplay will be used to create and open TrueCrypt and VeraCrypt volumes.
-- internal version of zuluplay will be used to create and restore TrueCrypt and VeraCrypt volume headers.
-- ---------------------------------------------------------------------------
```
This indicates that the internal code is used nevertheless...

I did build zuluplay without any configuration arguments, as i didn't see where were any (neither in your sources, nor in upstream tcplay sources) (cmake -LAH didn't reveal anything useful either).
Here is the config-log of my zuluplay:
```
=> zuluplay-1.1_1: running do_configure ...
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/lib/ccache/bin/cc
-- Check for working C compiler: /usr/lib/ccache/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/g++
-- Check for working CXX compiler: /usr/lib/ccache/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'devmapper'
--   Found devmapper, version 1.02.142
-- Checking for module 'uuid'
--   Found uuid, version 2.30.1
-- Looking for gcry_kdf_derive in gcrypt
-- Looking for gcry_kdf_derive in gcrypt - found
-- Configuring done
-- Generating done
-- Build files have been written to: /builddir/zuluplay-1.1/build

```

**Comment by mhogomchungu** [comment]
you configured zuluplay but you neither build it nor install it and hence zuluCrypt can not find it and that is why those two zuluplay config options makes no difference. zuluCrypt will use the bundled version because thats the only version it has access to.

zuluCrypt will have two options if you have zuluplay installed, it can use the system version or its bundled version and that option allows users to select which one of the two versions to use. The user will get this option only if they have zuluplay installed.

```-DINTERNAL_ZULUPLAY=true``` will cause zuluCrypt to unconditionally use its bundled version. This is useful if a user have zuluplay installed but prefers to use bundled version for some reason. This option is useful to me for testing since i need to have a way of testing both configurations.

```-DINTERNAL_ZULUPLAY=false``` will cause zuluCrypt to use system version if it is available and bundled version if system version is not available. 

Building a package from source code is a three step process. 
1. Configure.
2. Build
3. Install.

You have done the first one and you need to finish up with the remaining two and you do that by running:

1. make
2. sudo make install

The second one varies depending on your distribution, you may need to do su -c "make install" in other distributions.

**Comment by Piraty** [comment]
No need to explain the stages of a build process, but thanks anyway... I just cited the configure-output to show that is has no unmet depenencies. Of course i installed zuluplay on compile time of zulucrypt.

My understanding was this: -DINTERNAL_ZULUPLAY=false will neglect the bundled zPlay when compiling zCrypt and will link to the system's zPlay-lib.
Thanks to your explaination, that makes zPlay an optional _runtime_ dependency, you may state that somewhere eventually (at least i did not read it that way in the build instructions, therefore my question).

I am packaging for a distro, i will let you review my result if you like (in fact, we had discusion about it already: https://github.com/mhogomchungu/zuluCrypt/issues/53).

**Comment by mhogomchungu** [comment]
```
My understanding was this: -DINTERNAL_ZULUPLAY=false will neglect the bundled zPlay when compiling zCrypt and will link to the system's zPlay-lib.
```
Correct.

```
Thanks to your explaination, that makes zPlay an optional runtime dependency, you may state that somewhere eventually (at least i did not read it that way in the build instructions, therefore my question).
```

Not correct,zuluplay is a required compile time dependency.
There is a choice between system installed version of zuluplay and a bundled version of zuluplay and ```-DINTERNAL_ZULUPLAY``` option allows the user to choose which one to use.
