### ISSUE TITLE
TrayIcon sometimes not shown on login

### ISSUE THREAD

**Issue by andyboeh** [mhogomchungu/zuluCrypt#73]
I'm using zuluMount for a while now and I have added "zuluMount-Gui -e" to my startup applications. However, sometimes the trayicon is not shown. I had a similar problem in one of my projects, and I suspect a similar cause: The SystemTray is not yet ready and thus the icon cannot be added when zuluMount-Gui is started.

I'm utilizing a workaround in my projects which I took from the ownCloud desktop sync client: https://github.com/owncloud/client/blob/709aa27031f07ffbc21e0478ae0da220885a4cf3/src/gui/main.cpp#L146
This defers loading of the tray icon until the system tray is available.

Could a similar workaround be added to zuluMount as well?

Thanks

**Comment by mhogomchungu** [comment]
The git version has the same solution here[1].

The piece of code you posted looks like it has a bug. What happens when "attempts" variable is greater or equal to 30? The loop will keep on going and it will never end and the add will probably get stuck.

[1] https://github.com/mhogomchungu/zuluCrypt/blob/e0f1dee2774287db6d476da2b3feb6e71aa0e263/zuluCrypt-gui/utility.cpp#L1988

**Comment by andyboeh** [comment]
Thanks, than I'm going to wait until the git version ends up in my package manager (I'm on Arch) - sorry for the inconvenience.

Regarding ownCloud's code: I use a modified version in my projects, but I agree with you that I'm also not entirely sure whether it gets stuck - at least, if attempts >= 30, it displays a critical error.

**Comment by mhogomchungu** [comment]
If you are building zuluCrypt from this [1] aur then i thing rebuilding it again will fetch the latest git version.

[1] https://aur.archlinux.org/packages/zulucrypt-git
