### ISSUE TITLE
Config directory permissions are weird

### ISSUE THREAD

**Issue by jleclanche** [mhogomchungu/zuluCrypt#75]
```
drwxrwxrwx  2 adys users   4096 Oct 22 09:03 .zuluCrypt/

[9:05:32] adys@azura ~ % ls -al .zuluCrypt
total 36
drwxrwxrwx  2 adys users 4096 Oct 22 09:03 ./
drwx------ 21 adys users 4096 Oct 22 08:58 ../
-rw-r--r--  1 adys users    0 Oct 22 08:53 doNotshowWarning.option
-rw-rw-rw-  1 adys users   32 Oct 22 09:03 favorites
-rw-r--r--  1 adys users    8 Oct 22 08:53 FileManager
-rw-rw-rw-  1 adys users  475 Oct 22 08:58 plainDmCryptOptions
-rw-rw-rw-  1 adys users    1 Oct 22 08:53 tray
-rw-r--r--  1 adys users    0 Oct 22 09:03 zuluCrypt-gui.autoSetVolumeAsVeraCrypt
-rw-rw-rw-  1 adys users   28 Oct 22 09:05 zuluCrypt-gui-ui-options
-rw-rw-rw-  1 adys users    9 Oct 22 08:53 zuluCrypt.iconName
-rw-r--r--  1 adys users    1 Oct 22 08:53 zuluCrypt.scaleFactor
```

It looks like zuluCrypt is doing its own thing rather than respecting the system defaults, it's kinda weird.  The config directory itself def shouldn't be 0777.

**Comment by mhogomchungu** [comment]
These config options should be handled by QSettings. They are this way because i did not know what i was doing when i started and wasnt aware of QSettings class. The names of these config files should give clues of how clueless i was when i was setting them :-)

Then Debian/Ubuntu/Fedora wanted zuluCrypt to run in a "weird" mode i called "mixed mode".  This is where GUI components run root's privileged but they store their options in a user directory and this created a lot of problems as far as permissions where concerned and this explains the strange permissions of files and folders.

zuluCrypt 5.2.0 did away with the mixed mode and 5.3.0(to be released on Nov. 1st, 2017) will be 100% wayland ready since it will completely remove the necessity to run GUI components root privileged and i think this will be the time to move these settings to QSettings.

**Comment by mhogomchungu** [comment]
This one is no longer an issue since settings are now managed by QSettings object.
