### ISSUE TITLE
unnecessary duplicate of png icons (zulu*-gui)

### ISSUE THREAD

**Issue by Piraty** [mhogomchungu/zuluCrypt#81]
https://github.com/mhogomchungu/zuluCrypt/blob/722ec332f7ef80e30c0e45a43ff896875d2473be/zuluCrypt-gui/CMakeLists.txt#L143
https://github.com/mhogomchungu/zuluCrypt/blob/722ec332f7ef80e30c0e45a43ff896875d2473be/zuluMount-gui/CMakeLists.txt#L106

That copy of .png icons is probably unnecessary, as they already reside in `pixmaps` and `icons/hicolor/48x48/apps`.

**Comment by mhogomchungu** [comment]
I did this on purpose because i was not sure what DE picks up icons from what folder and decided to put the icons everywhere i could think of as a mean of making sure the icons will be picked up by everybody.

Some DE caches icons and this makes it harder when trying to figure out what path works and what path does not.

Is this causing a problem somewhere?

**Comment by Piraty** [comment]
no problem i know of, it's just redundant.
