### ISSUE TITLE
Unable to open volume in zulucrypt-gui

### ISSUE THREAD

**Issue by inhedgerow** [mhogomchungu/zuluCrypt#82]
Version 5.4.0 gives "Unrecognized ERROR with status number 127 encountered" when key is entered.  Any thoughts?  trying to get more info, both zuluCrypt-cli and zuluMount-cli give: error while loading shared libraries: libcryptsetup.so.4: cannot open shared object file: No such file or directory.  licryptsetup is available as libcryptsetup.so.12

**Comment by mhogomchungu** [comment]
I think the problem is due to zuluCrypt being build while installed version of cryptsetup was less than 2.0.0.

cryptsetup 2.0.0 is a major update and they changed the library name from "libcryptsetup.so.4" to  "libcryptsetup.so.12"

The solution is to simply rebuild zuluCrypt with the updated library. 

Added benefit of rebuilding zuluCrypt is the enabled ability to create LUKS2 volumes.

**Comment by inhedgerow** [comment]
You, sir, are a scholar and a gentleman (or other gender pronoun versions thereof)!  I shall make a note for others in the AUR for others.  Many thanks.
