### ISSUE TITLE
ubuntu 17.10 zulucrypt GUI: how to navigate to another harddrive?

### ISSUE THREAD

**Issue by hanswurst31** [mhogomchungu/zuluCrypt#89]
i want to navigate to another harddrive so i can create a encrypted container on it. how do i do it? when i go to "create container in a file" i can just navigate to "my computer"> after that there is just one harddrive selectable and that is he one where ubuntu is installed. the harddrive i want to navigate to is sda3. i thought maybe i have to look in the dev folder but there is no sda3 folder in it. propaply im wrong with this anyways.

thx!

**Comment by mhogomchungu** [comment]
Are you a new Linux user?

In Windows,you access a hard drive through a drive letter like "D:\"

In Linux you access hard drives through a mount point and your drive will have to be mounted first before zuluCrypt can access it. How to mount your drive is something that must happen outside of zuluCrypt and is dependent on the file manager you are using and i can not help you with because i do not use Ubuntu.

Alternatively, let zuluCrypt create the container file in your home directory(default location) and then move it later on to your preferred location.

**Comment by hanswurst31** [comment]
yes im new. the hdd is mounted allready(was present while installing ubuntu so i didnt have to do anything). with nautilus(explorer) i can access it with RW privilage. but its not visible in zulucrypt. therefore i cant use your recommended workaround for this because i cant navigate to the non ubuntu hdd via zulu.

what works though is to chose a whole drive to encrypt or mount. then every hdd/mount point is listed. but thats not what i want.

**Comment by mhogomchungu** [comment]
I can not follow your statements.

In my ubuntu 17.10 test system,two hard drives shows up on Nautilus as shown in image 1 below. Do both of your hard drive show up here?

These same two hard drives show up on the side bar of a file dialog window generated by zuluCrypt when clicking the folder icon shown in image 3. On this file dialog box,i can easily click to browse the external 52MB hard drive to put a volume created by zuluCrypt in.

![screenshot_20180116_142953](https://user-images.githubusercontent.com/3496115/34986929-7cb13f84-faca-11e7-9fb9-4ef2d790e0f7.png)

![ubuntu](https://user-images.githubusercontent.com/3496115/34986945-8826f4e4-faca-11e7-9455-4b57d99d6582.png)

![ubuntu1](https://user-images.githubusercontent.com/3496115/34986955-8d01f3c4-faca-11e7-94c9-1aa54bb804fc.png)

**Comment by hanswurst31** [comment]
image 1: yes
image 2: no

**Comment by mhogomchungu** [comment]
What you are seeing is like the image below and this is the native Qt file dialog window. My picture shows a desktop environment file dialog window. I do not know why you are getting that one.

If you can view the contents of your external hard drive then click the "my computer" icon and then the icon where ubuntu is installed and then browse to ```/media``` folder and one of the folders in there should be a path to your external hard drive,select one of the folder in there for zuluCrypt to use. 

![screenshot_20180116_162309](https://user-images.githubusercontent.com/3496115/34991090-679d0100-fad9-11e7-9ee1-c87efefa17cf.png)

**Comment by hanswurst31** [comment]
both are internal drives. one with ubuntu and the on i want to navigate to with windows on it. its like the native Qt file dialog window is restricted. /media/k28 is also empty. anyway to force zulucrypt to open in desktop enviroment mode?

**Comment by mhogomchungu** [comment]
Yes,the native Qt window is restricted and i do not know why you are getting it.

Did you find ```/media/k28``` to be empty ```after``` you have accessed the drive through your file manager?

what is the output of the following command
```
mount
```

**Comment by hanswurst31** [comment]
i didnt know that i had to enter the windows drive to be mounted because with right clicking on it i had the option unmount. after entering the windows drive /media/k28/ showing the windows partion so my actual problem seems to be solved. still it would be nice if i could get desktop environment.

**Comment by mhogomchungu** [comment]
I use plasma5(KDE) and the file dialog looks like below image where two hard drives are visibly present under "devices". That Qt dialog windows needs to be revisited but thats outside of what i can do in zuluCrypt.

Closing this one since the reported problem is solved.

![screenshot_20180116_185631](https://user-images.githubusercontent.com/3496115/34998029-08658ade-faef-11e7-9269-bc000d44765f.png)
