### ISSUE TITLE
Ubuntu 18.04 installation woes

### ISSUE THREAD

**Issue by mercertom** [mhogomchungu/zuluCrypt#95]
installing the 17.10 files creates dependency errors.
depends on libcryptsetup4
I actually  already have this installed from a libcrypt-dev, but then i get the .deb of libcryptsetup4.
It depends on libgcrypt11, for which there is no installation candidate, etc etc.

What's breaking this? I actually got it to run ok one time, but now with fix-broken install i've lost working zulucrypt.

**Comment by mhogomchungu** [comment]
What you are doing is very dangerous to your system.o

You are trying to install zuluCrypt version that was build specifically for ubuntu 17.10 on ubuntu 18.04.

Things breaking should be expected.

Best thing to do is to build zuluCrypt from sources[1] or wait until i provide packages for ubuntu 18.04. I do not know when i will do it because i depend on open suse build service to build packages for me and they currently do not offer it[2].

A third alternative is to use zuluCrypt packages provided by ubuntu. I believe they are using version 5.4.0 and this version should work fine on ubuntu.

If you are using zuluCrypt GUI, i can show you how to remove the annoying polkit prompt at start up if you find it annoying enough.

[1] https://github.com/mhogomchungu/zuluCrypt/blob/master/BUILD_INSTRUCTIONS
[2] https://build.opensuse.org/project/add_repository_from_default_list/home:obs_mhogomchungu

**Comment by mercertom** [comment]
I tried sudo apt install zulucrypt-gui, and I get Unrecognized Error with
status number 255 encountered when I try to mount a file.

**Comment by mhogomchungu** [comment]
1. What version of zuluCrypt was installed?
2. Did you get a polkit prompt when started the GUI?

**Comment by mercertom** [comment]
1. 5.4.0-2build1
2. no, and i dont know how to command the gui from command line.

Maybe a sudo zulucrypt-gui would solve the problem? "zulucrypt-gui" does nothing. i'm starting from the launcher. the window opens, i can select the volume, input password, then get the 255 error.

**Comment by mhogomchungu** [comment]
Will install ubuntu 18.04 and try to figure out what is going on later on today.

**Comment by mhogomchungu** [comment]
18.04 is not out yet!

I am on a limited bandwidth and i can not justify spending gigabytes of data to download unreleased version just to test this. This will have to wait until 18.04 is released because i will then know that the gigabytes of data i will download will last for months until 18.10 is released.

I think the only way forward for you for now is to build from source.

**Comment by mercertom** [comment]
Hey, no worries.

So I re-uninstalled and re-re-installed, and somehow either the updates to
18.04, the re-re-installed, or some random magic, and the packages from
plain sudo apt install zulucrypt-gui are working for now.

P.S. Where are you that the internet's so $$$? Can I mail you a flash drive
with new ubuntu versions and movies or tv shows or games or whatever every
few months? Is it just as expensive to send mail to where you are? PM me to
explore if it's a possibility.

On Mar 10, 2018 13:45, "mhogomchungu" <notifications@github.com> wrote:

18.04 is not out yet!

I am on a limited bandwidth and i can not justify spending gigabytes of
data to download unreleased version just to test this. This will have to
wait until 18.04 is released because i will then know that the gigabytes of
data i will download will last for months until 18.10 is released.

I think the only way forward for you for now is to build from source.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mhogomchungu/zuluCrypt/issues/95#issuecomment-372054416>,
or mute the thread

**Comment by mhogomchungu** [comment]
I am a Tanzanian national and i live in Tanzania. The nation is somewhere on the eastern part of Africa.

My internet plan gives me about 3GB of data a week and its good enough to download weekly episodes popular tv shows i want to watch and i think star trek discovery was pretty good if you are into that kind of show, live stream NBA games if i want to bother myself to be up at 3AM, watch all sorts of stuff on youtube and those other websites or a movie or two.

With 3GB of data a week, downloading and updating ubuntu 18.04 will take about half of it and that seems a bit too much.

zuluCrypt should be able to start paying for its expenses and best way to do that is to donate and donation info are available in the project's front page[1].

[1] https://mhogomchungu.github.io/zuluCrypt/

**Comment by mercertom** [comment]
Any advice for foreigners about internet or other stuff? Might be visiting
for a month this summer!

**Comment by mhogomchungu** [comment]
I lived in upstate New York for more than a decade and i was OK with internet service i was getting because i could stream netflix without buffering.

I am in Tanzania now and i am OK with internet service here because i can stream NBA games,watch youtube and other video services without buffering.

There are cell towers eeevvveeerrryywhere and i doubt if you visit here,you will find yourself anywhere without phone service. 

In think phone service in Tanzania is far superior compared to USA. Over here,you can buy a bundles on an hourly basis,weekly basis or month basis.

We did not invest massively in copper based connectivity forcing some people in some location to get internet and phone services only from certain providers like what happens in the US. Everything happens over cell towers here and people are free to choose from different provides any time.

You can buy bundles that offers talking time only, data only, both in a package or both but separately.

All phone services and traditional banks offers a service like m-pesa[1] and i think this kind of service is far better than credit card transactions.

I pay about one US dollar for the 3GB i am getting that expires after a week and i think this is pretty cheap and price wise,i think internet services here are very competitive. 

Closing this one since the original issue is now gone.

Thanks for the info that zuluCrypt 5.4.0 works fine in ubuntu 18.04.

[1] https://en.wikipedia.org/wiki/M-Pesa

**Comment by mercertom** [comment]
Also I did this to disable polkit: https://askubuntu.com/questions/614534/disable-authentication-prompts-in-15-04

**Comment by mhogomchungu** [comment]
Importing computers and other personal electronic devices to Tanzania is tax free because the government want to encourage economic activities that depends on them. The expensive part comes from our currency loosing ground against foreign currently. I do not remember being unable to buy any electronic device i wanted because nobody was selling it here in Tanzania. Thanks for the offer but i am looking to buy any electronic device or anything else from abroad.

The thing i hate the most in "modern linux" is polkit and d-bus is next in line. To me, these technologies seem opaque and intentionally difficult to understand and configure. 

Thanks for the tip about a one stop solution that shuts down polkit prompts once and for all. What i knew before and using is going to "/usr/share/polkit-1/actions" and then look for the polkit policy file of a project i want to auto enable polkit authorization and change  in them "<allow_active>auth_admin</allow_active>" to "<allow_active>yes</allow_active>"

For example, to make zuluCrypt work without generating the polkit prompt at start up, i replaced the contents of "/usr/share/polkit-1/actions/org.zulucrypt.zulupolkit.policy" with

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>

  <action id="org.zulucrypt.zulupolkit">
    <message>Authentication is required to complete requested operation.</message>
    <icon_name>zuluCrypt</icon_name>
    <defaults>
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/zuluPolkit</annotate>
  </action>

</policyconfig>
```
