### ISSUE TITLE
OSB repo outdated

### ISSUE THREAD

**Issue by KAMiKAZOW** [mhogomchungu/zuluCrypt#99]
https://build.opensuse.org/package/show/home:mhogomchungu/zuluCrypt is broken on various levels:

* I fixed Fedora and openSUSE builds: https://build.opensuse.org/request/show/604044
* Please remove end-of-life distributions such as Fedora 24–26, openSUSE 13.x
* Add Fedora 28 and openSUSE Leap 15.0

**Comment by mhogomchungu** [comment]
Its been a while since i could build binaries and i was holding off trying to resolve the issue until when i want to make a new release.

Thanks for looking into this and solve the problem. Now, i am not exactly sure what i am supposed to do. What must i do to incorporate the improvements you made?

**Comment by KAMiKAZOW** [comment]
In case you're logged in, you have an "Accept Request" button right below the "My Decision" comment box.

**Comment by mhogomchungu** [comment]
You used a wronge account, i plan to delete this account soon because debian packages created by this account uses sha1 and debian and ubuntu both rejects them.

The account you should have made your pull request with is: https://build.opensuse.org/package/show/home:obs_mhogomchungu/zulucrypt

Notice the difference between ```obs_mhogomchungu``` and ```mhogomchungu```

The two account should be identical, i created the ```obs_mhogomchungu``` account and dublicate everything just to force package creation with sha256.

**Comment by KAMiKAZOW** [comment]
https://build.opensuse.org/request/show/604420

**Comment by mhogomchungu** [comment]
accepted
